#!gmake
#
# $Header: //depot/main/gfx/lib/opengl/drivers/DDX/GNUmakefile#6 $

SUBDIR = drivers/DDX

CFILES =	     \
	ddxcx.c	     \
	ddxrgb.c     \
	ddxci.c	     \
	ddxscreens.c \
	$(NULL)

include $(GFXDIR)/defs/subdefs

headers headers_install apps:

libs libs_install install: default
