#!gmake
#
# $Header: //depot/main/gfx/lib/opengl/glcore/GNUmakefile#13 $

SUBDIR = glcore

CFILES = \
	dl_block.c \
	dl_heap.c \
	dl_init.c \
	dl_list.c \
	dl_mopt.c \
	dl_opt.c \
	dl_pplst.c \
	dl_splc.c \
	dl_splst.c \
	dl_table.c \
	px_api.c \
	px_cmatrix.c \
	px_hist.c \
	px_convol.c \
	px_mod.c \
	px_pack.c \
	px_paths.c \
	px_read.c \
	px_rend.c \
	px_upack.c \
	s_accum.c \
	s_atest.c \
	s_attrib.c \
	s_bitmap.c \
	s_blend.c \
	s_btdraw.c \
	s_buffer.c \
	s_capi.c \
	s_ci.c \
	s_clear.c \
	s_clip.c \
	s_contxt.c \
	s_convol.c \
	s_cpydsp.c \
	s_ctable.c \
	s_depth.c \
	s_dlist.c \
	s_eval.c \
	s_export.c \
	s_feed.c \
	s_finish.c \
	s_fog.c \
	s_get.c \
	s_global.c \
	s_hist.c \
	s_image.c \
	s_lcache.c \
	s_lcomp.c \
	s_light.c \
	s_lnclip.c \
	s_lndraw.c \
	s_lnfast.c \
	s_lnfin.c \
	s_lnspan.c \
	s_math.c \
	s_memmgr.c \
	s_names.c \
	s_napi.c \
	s_pgaa.c \
	s_pgclip.c \
	s_pgdraw.c \
	s_pgfin.c \
	s_pgmode.c \
	s_pgspan.c \
	s_pick.c \
	s_prim.c \
	s_ptaa.c \
	s_ptdraw.c \
	s_ptfin.c \
	s_rapi.c \
	s_rect.c \
	s_rgb.c \
	s_rpos.c \
	s_select.c \
	s_size.c \
	s_span.c \
	s_sten.c \
	s_store.c \
	s_tapi.c \
	s_tex.c \
	s_texel.c \
	s_texextr.c \
	s_texfmt.c \
	s_texmgr.c \
	s_trap.c \
	s_vapi.c \
	s_varray.c \
	s_vertex.c \
	s_xform.c \
	s_zfuncs.c \
	vc_cache.c \
	vc_line.c \
	vc_point.c \
	vc_poly.c \
	$(NULL)

include $(GFXDIR)/defs/subdefs

headers headers_install apps:

libs libs_install install: default
